apiVersion: v1
kind: Service
metadata:
  name: mdai-event-hub-websockets
  namespace: mdai
  labels:
    app: mdai-event-hub
spec:
  selector:
    app: mdai-event-hub
  ports:
    - port: 4320
      name: websockets-port
      protocol: TCP
      targetPort: 4320
  type: ClusterIP

