apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        - name: POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        - name: HTTP_PORT
          value: "{{ .Values.deployment.containerPort }}"
        - name: VALKEY_AUDIT_STREAM_EXPIRY_MS
          value: "{{ .Values.auditStreamExpiryMs }}"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "{{ .Values.otelExporterOtlpEndpoint }}"
        - name: VALKEY_AUDIT_STREAM_RETENTION
          value: "{{ .Values.auditStreamRetention }}"
        - name: OTEL_SDK_DISABLED
          value: "{{ .Values.otelSdkDisabled }}"
        - name: VALKEY_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: VALKEY_ENDPOINT
              name: valkey-secret
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: VALKEY_PASSWORD
              name: valkey-secret
        - name: NATS_URL
          value: {{ include "mdai.natsUrl" . | quote }}
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: NATS_PASSWORD
              name: nats-secret
        - name: LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        - name: HOP_LIMIT
          value: "{{ .Values.hopLimit | default 2 }}"
