apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - name: {{ .Values.opamp.name }}
      protocol: TCP
      port: {{ .Values.opamp.port }}
      targetPort: {{ .Values.opamp.targetPort }}

  type: {{ .Values.service.type }}
