# Use to set a custom valkey audit stream expiration (MINID)
# auditStreamExpiryMs: 3600000

natsUrl: nats://mdai-nats.mdai.svc.cluster.local:4222

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "mdai-event-hub"

deployment:
  name: mdai-event-hub
  replicas: 3
  containerPort: 8082
  opampPort: 4320
  tolerations: []
  nodeSelector: {}
  affinity: {}
  annotations: {}
image:
  repository: public.ecr.aws/p3k6k6h3/mdai-event-hub
  # tag: 0.0.1

service:
  name: mdai-event-hub
  port: 8082
  targetPort: 8082
  type: ClusterIP

opamp:
  name: mdai-event-hub-opamp
  port: 4320
  targetPort: 4320
