name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:
  ci:
    uses: decisiveai/ci/.github/workflows/go-lint-test.yml@fac4b525631808bac63173e9c732e741d43fe637
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      PLATFORM_HEALTH_ACCESS_APP_ID: ${{ secrets.PLATFORM_HEALTH_ACCESS_APP_ID }}